[package]
name = "srfinder"
version = "2.0.0"
authors = ["Acizza <jonathanmce@gmail.com>"]

[dependencies]
rocket         = "0.3"
rocket_codegen = "0.3"
serde          = "1.*"
serde_derive   = "1.*"
reqwest        = "0.7"
csv            = "1.0.0-beta.3"
error-chain    = "0.10"
time           = "0.1"
rand           = "0.3"

[dependencies.rocket_contrib]
version          = "0.3"
default-features = false
features         = ["json", "handlebars_templates"]